server:
  port: 8082

logging:
  # 设置日志输出格式
  pattern:
    console: level-%level %msg%n
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.abc.provider: debug


spring:
  application:
    name: alan-provider-8082   # 暴露微服务名称 在没有instance.instance-id的时候暴露的就是 ip+name+端口

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.104.255.5:3306/cloud_test?useUnicode=true&amp;characterEncoding=utf8&useSSL=false
    username: root
    password: root



# 指定Eureka服务中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka # 这里是eureka-server的地址
      # defaultZone: http://eureka8100.com:8100/eureka,http://eureka8200.com:8200/eureka,http://eureka8300.com:8300/eureka
  instance:
    instance-id: alan-provider-8082


info:
  company.name: www.alan.com
  company.addr: China ShangHai
  company.tel: 17621142248
  app.name: cloud-provider01
  app.desc: mic-server-cloud
  author: alan.liu